apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: codeforces
data:
  # Service URLs - using internal cluster DNS for ClusterIP services
  AUTH_SERVICE_URL: "http://auth-service.codeforces.svc.cluster.local:80"
  CONTEST_SERVICE_URL: "http://contest-service.codeforces.svc.cluster.local:80"
  SUBMISSION_SERVICE_URL: "http://submission-service.codeforces.svc.cluster.local:80"
  LEADERBOARD_SERVICE_URL: "http://leaderboard-service.codeforces.svc.cluster.local:80"

